// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVw79cwT_JR1N1pTYUIIaYuVoFehPITJI',
    appId: '1:379214372274:web:f87c4d54737c26f7cd98ab',
    messagingSenderId: '379214372274',
    projectId: 'futconecta',
    authDomain: 'futconecta.firebaseapp.com',
    storageBucket: 'futconecta.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqm3skUjudCqsW8K5Zj4XXXHx_lbM9610',
    appId: '1:379214372274:android:e3ad16197d0b8829cd98ab',
    messagingSenderId: '379214372274',
    projectId: 'futconecta',
    storageBucket: 'futconecta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq8PCUw9DWb8rG3rhFHeB2kwMqSuuvDx4',
    appId: '1:379214372274:ios:b7419e4d05505b2ccd98ab',
    messagingSenderId: '379214372274',
    projectId: 'futconecta',
    storageBucket: 'futconecta.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq8PCUw9DWb8rG3rhFHeB2kwMqSuuvDx4',
    appId: '1:379214372274:ios:b7419e4d05505b2ccd98ab',
    messagingSenderId: '379214372274',
    projectId: 'futconecta',
    storageBucket: 'futconecta.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVw79cwT_JR1N1pTYUIIaYuVoFehPITJI',
    appId: '1:379214372274:web:b413c1e353ea374bcd98ab',
    messagingSenderId: '379214372274',
    projectId: 'futconecta',
    authDomain: 'futconecta.firebaseapp.com',
    storageBucket: 'futconecta.firebasestorage.app',
  );
}
